### ISSUE TITLE
Sorting after find not working

### ISSUE THREAD

**Issue by steveAllen0112** [airmoi/FileMaker#11]
Used

`$q = $db ->newFindCommand('layoutname');`
`$q -> addFindCriterion('field','value');`
`$q -> addSortRule('field',1,FILEMAKER_SORT_DESCEND);`

`$r = $q -> execute();`

It throws a 108, "Value list is missing" error.  Commenting out the sort lines, it doesn't throw the error.  Trace shows error thrown at the execute().

One of the sort fields (I have three sort lines) has a value list on it, but even when I remove that one from the sort, and even take it off the field on the layout (set the field back to "Edit box" instead of "Drop-down list"), so that none of the sorts have value lists, the error is still thrown.

**Comment by steveAllen0112** [comment]
Oh, and on top of that, it's not actually _throwing_ the error, but continues execution, with the result in $r being a FileMakerException object.

**Comment by airmoi** [comment]
Hi Steven, I wasn't able to reproduce the issue.
Can you send me a sample file ?

Also, do you have any "validation" rule on those fields which requires a value list that could be not accessed over php (i.e no view privilege)

**Comment by steveAllen0112** [comment]
I will have to mock a file up, since the DB in question is under NDA.  I will do so later today, or tomorrow.

There are no validations on the fields in the sort.

**Comment by steveAllen0112** [comment]
In the meanwhile, here's the code section in question.


```
try {
	$courses = $mfs -> newFindCommand('web_courses');
	$courses -> addFindCriterion('flag_available','==Available');
	$courses -> addFindCriterion('flag_show_on_web','1');

	$courses -> addSortRule('category',1,FILEMAKER_SORT_DESCEND);
	$courses -> addSortRule('length',2,FILEMAKER_SORT_DESCEND);
	$courses -> addSortRule('name_for_selection',3,FILEMAKER_SORT_DESCEND);

	$coursesResult = $courses -> execute();

	require(dirname(__FILE__).'/../includes/php/_courses.php');

	$coursesArr = obtainCourses($coursesResult);
}catch(Exception $e){
	$code = $e->getCode();
	if($code !== 401){
		http_response_code(503);
	}
	error($code,$e->getMessage());
}
```

**Comment by steveAllen0112** [comment]
I just got a report of the same problem in a completely different project, server, database, everything.

Code is:

```
$q = $db ->newFindCommand('web_reports');
$q ->addFindCriterion('_idCON.requestedBy', '=='.$userProfile['idCON']);
$q ->addSortRule('timestamp.requested', 1, FILEMAKER_SORT_DESCEND);

$r = $q ->execute();
```

I'll try to get that example file to you today.

**Comment by airmoi** [comment]
Hi,

Did you solve the issue ?
If not, can you provide a sample file ? Also, you may test the generated url (using $fm->lastRequestedUrl) in you brother to see if there is no issue with CWP answer

**Comment by steveAllen0112** [comment]
I'll try that.

**Comment by airmoi** [comment]
Any news on this issue ?

**Comment by steveAllen0112** [comment]
I have not been able to resolve this any way I've tried.  It is consistent on multiple, completely unrelated projects.

It's not difficult to mock up a file for this.  Just use a standard template file, and do a find on it from PHP using this library and the `newFindCommand()'.  Add a criterion or two, and a sort rule or two, using `addSortRule()`, and it returns `Code: 108, Message: "Value list is missing."`

Every time.

**Comment by airmoi** [comment]
Ok I just figured out where is your issue : 
You are using "FILEMAKER_SORT_ASCEND/DESCEND" constants which have been removed.

PHP may warn you with a notice that theses constant does not exists, and convert it as literal string "FILEMAKER_SORT_ASCEND"
The 108 code is a bit wired, but this is FileMaker's CWP answer when using an invalid sort param.

To fix this, just use FileMaker::SORT_ASCEND/FileMaker::SORT_DESCEND

**Comment by steveAllen0112** [comment]
Ok, that makes sense. I will implement on mine.

question: Why were those constants removed?  (I mean, I can always add them back myself, in my config code, but still...curious.)
