### ISSUE TITLE
Incorrect FileMakerException being thrown

### ISSUE THREAD

**Issue by mrchimp** [airmoi/FileMaker#13]
In `src/FileMaker.php` on line 811 a `FileMakerException` is being triggered and is being passed the curl error number as the error code. For me this number is 7 (CURLE_COULDNT_CONNECT) but in `FileMakerException.php` this is being interpreted as FileMaker error 7 (Running out of memory). I assume this is also wrong for the other Curl errors in previous lines in FileMaker.php.

**Comment by MatthiasKuehneEllerhold** [comment]
See: https://github.com/airmoi/FileMaker/pull/12
This seems to be fixed in develop but sadly its not released yet.

**Comment by mrchimp** [comment]
Ah, somehow I didn't spot that issue!

**Comment by airmoi** [comment]
I've just released a new version that solve this issue.
Checkout [release note](https://github.com/airmoi/FileMaker/releases/tag/2.2.0) for more infos
