### ISSUE TITLE
"empty" values count as not being set

### ISSUE THREAD

**Issue by mrchimp** [airmoi/FileMaker#15]
I'm trying create a new record with a value set to `0`. This is is being marked as invalid because of the `RULE_NOTEMPTY` rule.

I believe this is because `empty()` is being used (in field.php, line 112) to check whether the value has been set which will return true for `""`, `0`, `"0"` `null`, `false`, `[]` etc.

I'm not sure of the right way to get around this. It seems that if a value isn't set then `null` gets passed to this `validate()` method so we could maybe use `is_null()` instead. This could have other side effects but it seems like `null` is the actual "not set" value.

I'm happy to make a pull request if you think this is the right way to go about it.

**Comment by airmoi** [comment]
Hi,

Thanks for reporting thing one.
Seems to be a legacy issue from the original API.

I will fix it asap

**Comment by airmoi** [comment]
Released hotfix in the master branch
