### ISSUE TITLE
Issue with setFieldFromTimestamp

### ISSUE THREAD

**Issue by gRegorLove** [airmoi/FileMaker#17]
In the Edit Command ([source](https://github.com/airmoi/FileMaker/blob/master/src/Command/Edit.php#L188)), `setField` is called passing the `$field` object, but `setField` is expecting a string. I have not tested yet, but I think changing to `$field->getName()` there will work. Alternately, adding a conditional check in `setField` for whether an object or string is passed in.

**Sample Code**
prevalidate option is set to true in the FM connection.
```
$EditCommand = $fm->newEditCommand($layout, $record_id);
$EditCommand->setFieldFromTimestamp('token_expires', time());
```

**Warnings and Error**

```
Warning: preg_match() expects parameter 2 to be string, object given in ...airmoi/filemaker/src/Command/Edit.php on line 127

Warning: Illegal offset type in isset or empty in ...airmoi/filemaker/src/Object/Layout.php on line 86

Warning: strpos() expects parameter 1 to be string, object given in ...airmoi/filemaker/src/Object/Layout.php on line 89

Catchable fatal error: Object of class airmoi\FileMaker\Object\Field could not be converted to string in ...airmoi/filemaker/src/Object/Layout.php on line 94
```

**Comment by airmoi** [comment]
Hi @gRegorLove ,

Thanks for reporting this issue.
A fix has been released
