### ISSUE TITLE
Incorrect exception being thrown in Add.php and Record.php + seeming mistake in FileMaker.php createRecord

### ISSUE THREAD

**Issue by joleksow** [airmoi/FileMaker#2]
Hello,

I noticed a pattern in both Add.php and Record.php in the setField method that is throwing exceptions incorrectly, specifically this code:

```php
function setField($field, $value, $repetition = 0) {
        if ( !array_search($field, $this->fm->getLayout($this->_layout)->listFields()))
                throw new FileMakerException($this->fm, 'Field "'.$field.'" is missing');
```
Since the array is numeric indexed, array_search will occasionally return a value of 0 when the field being added is the first one in the array. This makes the conditional true even though the field was found. 

I believe the following is what should be included:

```php
function setField($field, $value, $repetition = 0) {
        if ( array_search($field, $this->fm->getLayout($this->_layout)->listFields()) === false)
                throw new FileMakerException($this->fm, 'Field "'.$field.'" is missing');
```

Checking explicitly for boolean false.

The other issue I discovered was with FileMaker.php's createRecord method:

```php
public function createRecord($layout, $fieldValues = array()) {
        $layout = $this->getLayout($layoutName);
```

I believe the method parameter should be $layoutName instead of $layout, correct?

**Comment by airmoi** [comment]
Hi joleksow,

Thank you for your feedback. I've fixed it.

**Comment by joleksow** [comment]
Thanks for the quick attention to this!
