### ISSUE TITLE
Call to undefined method FileMakerException::getField() in Command\Add->setField()

### ISSUE THREAD

**Issue by aadmathijssen** [airmoi/FileMaker#24]
When using the module with `errorHandling => default`, a call to `\airmoi\FileMaker\Command\Add::setField` results in the following error in case there problems obtaining the FileMaker layout:

```
Call to undefined method airmoi\FileMaker\FileMakerException::getField()' in /path/to/vendor/airmoi/filemaker/src/Command/Add.php:98
```

The line reads as follows:

```
 $fieldInfos = $this->fm->getLayout($this->layout)->getField($field);
```

The problem here is that the `getLayout` method might return a `FileMakerException`. But on this class, the `getField` method is not defined.

The straightforward solution to this is to use the `FileMaker::isError` method on the result of the `getLayout` method. When the `isError` method returns `true`, the method should continue in the same fashion as when the `getField` method returns a `FileMakerException`.

This issue seems to occur at other places where `getField` method is called on the result of `getLayout`, namely in the following methods:

* `\airmoi\FileMaker\Command\Add::execute`
* `\airmoi\FileMaker\Command\Add::setFieldFromTimestamp`
* `\airmoi\FileMaker\Command\Command::validate`
* `\airmoi\FileMaker\Command\CommandTrait::getFieldResult`
* `\airmoi\FileMaker\Command\Edit::execute`
* `\airmoi\FileMaker\Command\Edit::setField`

**Comment by olekrisek** [comment]
This also happens if you try to edit an field that happens to not be on the layout. 

`PHP Fatal error:  
Uncaught Error: Call to undefined method airmoi\FileMaker\FileMakerException::isGlobal() 
in <path>/lib/FileMaker/src/Command/Edit.php:93`
