### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'FileMaker' not found in ...

### ISSUE THREAD

**Issue by Mommoti** [airmoi/FileMaker#29]
Hi 
I have this error when I use FileMaker::SORT_ASCEND/FileMaker::SORT_DESCEND

**Comment by airmoi** [comment]
Hi, did you add "use airmoi\filemaker" statement in your file?

**Comment by Mommoti** [comment]
Yes, of course.
This is the code:


$findCommand -> addFindCriterion("aFK_PropertyID_IDCasa", $Propid );

$findCommand -> addSortRule('To_Al',1,FileMaker::SORT_DESCEND);

$result2 = $findCommand->execute();

$records2 = $result2->getRecords();

**Comment by Mommoti** [comment]
And this is the dblogin.php (called with “include” at the begging of script)

<?php

require './FileMaker/autoloader.php';

use airmoi\FileMaker\FileMaker;

use airmoi\FileMaker\FileMakerException;

use airmoi\FileMaker\FileMakerValidationException;

$database = 'xxxxxxxxxx';

$host = 'http://xxxxxxxx';

$username = 'xxxxxxx';

$password = 'xxxxxxx';

$fm = new FileMaker($database, $host, $username, $password);

?>

**Comment by Mommoti** [comment]
I find the solution: this lines MUST be in the same file script where there is the FileMaker request
require './FileMaker/autoloader.php';
use airmoi\FileMaker\FileMaker;
use airmoi\FileMaker\FileMakerException;
use airmoi\FileMaker\FileMakerValidationException;

**Comment by airmoi** [comment]
The "use" statement should be called in any files that while call the class according to namespaces specification (http://php.net/manual/en/language.namespaces.basics.php).

If no use statement is present in the file, you may also directly call the class by using its full namespace (ie airmoi\FileMaker\FileMaker::SORT_ASCEND)
