### ISSUE TITLE
Issues with CompoundFind

### ISSUE THREAD

**Issue by joleksow** [airmoi/FileMaker#3]
Hey Romain,

I was trying to work with the CompoundFind command and discovered a couple of issues:

\Command\CompoundFind execute()
Line 114
```php
$findCriterias = $request->findCriteria;
```

Issue: \airmoi\FileMaker\Command\Find does not have a $findCriteria property. It has a protected $_findCriteria that cannot be accessed directly from the CompoundFind command. Recommend adding getter method if this is needed.

Line 135
```php
$nextRequest = $this->_requests[$requestCount];
if ($nextRequest->omit == true) {
```

Issue: \airmoi\FileMaker\Command\Find does not have an $omit property. It does have a protected $_skip property. If this is needed in the CompoundFind command, recommend adding a getter.

After I put in some quick hacks related to these two things the CompoundFind command worked just fine. Could you please take a look at this and update when you have a chance?

Thanks!
John

**Comment by airmoi** [comment]
Hi joleksow,

The CompoundFind object must be used with the FindRequest Object.
Find and CompoundFind are distinct actions and can't be used together (this is the original PHP-API behavior)

Have a look to the test script file "simpletest.php" at line 177 to see how to use CompoundFile.

Airmoi
