### ISSUE TITLE
Fetching base64-encoded data

### ISSUE THREAD

**Issue by Dronki** [airmoi/FileMaker#40]
Fetching an image that has been base64-encoded seems to cause the library to max out memory.
```
EXCEPTION : - At :/Users/rickard/Desktop/WPFM/vendor/airmoi/filemaker/src/FileMaker.php line 1145 - Code :0 - Message :XML error: No memory at line 142592 - Stack :#0 /Users/rickard/Desktop/WPFM/vendor/airmoi/filemaker/src/Parser/FMResultSet.php(80): airmoi\FileMaker\FileMaker->returnOrThrowException('XML error: No m...') #1 /Users/rickard/Desktop/WPFM/vendor/airmoi/filemaker/src/Command/Command.php(265): airmoi\FileMaker\Parser\FMResultSet->parse('getResult('execute() #4 {main} 
```
How to reproduce this:  
Encode an image with base64, store it in a field.  
Fetch that field from a layout.

Let me know what you might need to reproduce this issue :)

**Comment by airmoi** [comment]
Yes, there is a limitation in the XML library that prevent big XML to be parsed.

However, why not using the dedicated "getContainerData" method to get your file as a container instead of using an base64 encoded field ?

**Comment by carlotta11** [comment]
Is it possible that this is why I can't write long text in a text field? After about 150 words it stops - after that the response from Filemaker takes at least 15 seconds and nothing is saved. How can I make this possible? There is a field where I have to save a long text (up to 700 words).
