### ISSUE TITLE
Is there a function to end a connection?

### ISSUE THREAD

**Issue by wooddewweb** [airmoi/FileMaker#41]

**Comment by airmoi** [comment]
No,

The legacy PHP-API does not include any method to end a connection (because there is no method to end a session in CWP)

However, I may add such feature later for dataAPI support

**Comment by wooddewweb** [comment]
Hi,

I managed as follows, before I was having 30 active connections, now only one, at most two connections. :)

Thanks and it would be nice to put this resource to the PHP community.


try {

     $fm = new FileMaker(ALFA_DATABASE, ALFA_IP, ALFA_USER, ALFA_PASSWORD);
                
     // your code
     
     
     //close session
     $fm->endProfile('IrG6U+Rx0F5bLIQCUb9gOw==');  <-- Session src/FileMaker.php
     $fm->logout();
   
 } catch (FileMakerException $e) {
       // your code
} catch (Exception $e) {
       // your code
}

**Comment by airmoi** [comment]
Hi,

I don't get how the endProfile method could have anything to do with the session handling, this is something related to the "log" system.

Custom Web Publishing used to have a "session cookie" at the very beginning, but it's support was drop.
Connections are managed by the server that choose to reuse them or not depending on its own "internal logic". There is nothing we can do on our side.

**Comment by wooddewweb** [comment]
Hey,


Thanks for listening!
Well at least in my APP it worked as reported, thus eliminating sessions were rushed.

**Comment by airmoi** [comment]
You can logout from a dataAPI session using the FileMaker::dataApiLogout() method

`$fm->dataApiLogout();`
