### ISSUE TITLE
Expected type Error ?

### ISSUE THREAD

**Issue by zhuusheng** [airmoi/FileMaker#43]
In the FileName "sample.php", i have an error "Expected type 'Countable|array'. Found 'string'.intelephense(1006)
@var string $container [256,17]".

and other,

In the FileName "FileMaker.php", i have an error "Expected type 'CurlHandle'. Found 'airmoi\FileMaker\Resource'.intelephense(1006) [956,29]".

i don't how to handle it, please tell me, 

THANKS ALL.

**Comment by airmoi** [comment]
The sample.php is deprectated and only aims to be an example of usage.

If you have the same issue in your code, please post a sample of your code
