### ISSUE TITLE
X-FMI-PE-ExtendedPrivilege header

### ISSUE THREAD

**Issue by nd1312** [airmoi/FileMaker#44]
Hello.
How exactly does this header / FM setting work? How is the value generated?  
  
We're using an ancient Filemaker PHP API and wanted to upgrade to this one.
It doesn't work (error 959), because the X-FMI-PE-ExtendedPrivilege header is different than in the old API.

If i manually change it to the old value, or if I remove the header it works.  
  
Is this something we can / have to configure on our FileMaker Server?  (We're using v11.0.3.302)
Would it be possible to add it as an option to the FileMaker class?  

I got it to work by overwriting the CURLOPT_HTTPHEADER via "curlOptions", but that's not a great solution of course

**Comment by airmoi** [comment]
Hi,

I wasn't aware of that change in the PHP-API when Filemaker was upgraded to v12+.
The X-FMI-PE-ExtendedPrivilege is a constant defined by FileMaker to distinguish classic XML vs PHP requests.

I won't change the core code as it aims to be compatible with version 16+ only and won't be tested for lower versions.
However, you may create a fork to change this constant in  code.
